<?php
//eksc: copied from tripal_feature; purpose as yet unknown
/**
 * Implements hook_disable().
 * Disable default views when module is disabled
 *
 * @ingroup legume_qtl
 */
function legume_qtl_disable() {

  // Disable all default views provided by this module
  require_once("legume_qtl.views_default.inc");
  $views = legume_qtl_views_default_views();
  foreach (array_keys($views) as $view_name) {
    tripal_disable_view($view_name,FALSE,array('suppress_error' => TRUE));
  }
}

//eksc: copied from tripal_features
/**
 * Implements hook_requirements().
 *
 * @ingroup legume_qtl
 */
function legume_qtl_requirements($phase) {
  $requirements = array();
  if ($phase == 'install') {
    // make sure chado is installed
    if (!$GLOBALS["chado_is_installed"]) {
      $requirements ['legume_qtl'] = array(
          'title' => "legume_qtl",
          'value' => "ERROR: Chado must be installed before this module can be enabled",
          'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  return $requirements;
}

/**
 * Implementation of hook_install().
 */
function legume_qtl_install() {
   // create the module's data directory
   tripal_create_moddir('legume_qtl');
   
   // add the materializedviews
   legume_qtl_add_qtl_search_mview();
   
   // we want to integrate the materialized views so that they
   // are available for Drupal Views, upon which our search forms are built
   legume_qtl_views_integrate_qtl_search();
}

/**
 * Implementation of hook_uninstall().
 */
function legume_qtl_uninstall() {
  
  // Drop the MView table if it exists
  $mview_id = tripal_mviews_get_mview_id('qtl_search');
  if ($mview_id) {
    tripal_mviews_action("delete", $mview_id);
  }
}

/**
 * Add the qtl_search materialized view 
 */
function legume_qtl_add_qtl_search_mview() {
  // Populates the table qtl_search
  $sql = "
    SELECT 
      q.feature_id AS qtl_id,
      cf.nid AS qtl_nid,
      q.name AS qtl_name,
      pq.name AS expt_qtl_symbol,
      o.genus || ' ' || o.species AS organism,
      o.common_name,
      co.nid AS organism_nid,
      m.accession AS mnemonic,
      p.uniquename AS citation,
      cp.pub_id AS pub_nid,
      etn.value AS expt_trait_name,
      etd.value AS expt_trait_description,
      tu.value AS trait_unit,
      tc.trait_class,
      tc.qtl_symbol,
      tn.trait_name,
      tc.trait_description,
      tn.obo_terms,
      s.name AS favorable_allele_source,
      cs.nid AS fas_nid,
      tmt.value AS treatment,
      meth.value AS method,
      lod.rawscore AS lod,
      lr.rawscore AS likelihood_ratio, 
      mr2.rawscore AS marker_r2, 
      tr2.rawscore AS total_r2, 
      add.rawscore AS additivity,
      nm.name AS nearest_marker, 
      cnm.nid AS nearest_marker_nid, 
      fml.name AS flanking_marker_low,
      cfml.nid AS flanking_marker_low_nid,
      fmh.name AS flanking_marker_high,
      cfmh.nid AS flanking_marker_high_nid,
      comm.value AS comment
    
    FROM feature q
    
      -- get nid for QTL feature
      INNER JOIN public.chado_feature cf ON cf.feature_id = q.feature_id
    
      INNER JOIN organism o ON o.organism_id=q.organism_id
      INNER JOIN public.chado_organism co ON co.organism_id = o.organism_id
      INNER JOIN organism_dbxref mx ON mx.organism_id=o.organism_id
      INNER JOIN dbxref m ON m.dbxref_id=mx.dbxref_id 
           AND m.db_id=(SELECT db_id FROM db WHERE name='uniprot:species')
           
      -- experiment and publication
      INNER JOIN feature_project fp ON fp.feature_id=q.feature_id
      INNER JOIN project e ON e.project_id=fp.project_id
      INNER JOIN project_pub pp ON pp.project_id=e.project_id
      INNER JOIN pub p ON p.pub_id=pp.pub_id
      INNER JOIN public.chado_pub cp ON cp.pub_id=p.pub_id
        
      -- QTL name used in publication
      LEFT JOIN feature_synonym pqs ON pqs.feature_id=q.feature_id
      LEFT JOIN synonym pq ON pq.synonym_id=pqs.synonym_id
    
      -- experiment trait name
      INNER JOIN featureprop etn ON etn.feature_id = q.feature_id
        AND etn.type_id=(SELECT cvterm_id FROM chado.cvterm 
                         WHERE name='Experiment Trait Name'
                               AND cv_id=(SELECT cv_id FROM chado.cv 
                                          WHERE name='feature_property'))
                             
      -- experiment trait description
      LEFT JOIN featureprop etd ON etd.feature_id = q.feature_id
        AND etd.type_id=(SELECT cvterm_id FROM chado.cvterm 
                                WHERE name='Experiment Trait Description'
                                      AND cv_id=(SELECT cv_id FROM chado.cv 
                                                 WHERE name='feature_property'))
                                 
      LEFT JOIN featureprop tu 
        on tu.feature_id=q.feature_id
           and tu.type_id=(select cvterm_id from cvterm
                            where name='Trait Unit'
                                  and cv_id=(select cv_id from cv
                                             where name='feature_property'))
    
      -- trait class
      LEFT JOIN (
        SELECT symf.feature_id, sym.name AS qtl_symbol, 
               sym.definition AS trait_description, t.name AS trait_class
        FROM feature q2 
          -- get QTL symbol 
          LEFT JOIN feature_cvterm symf ON symf.feature_id=q2.feature_id 
          LEFT JOIN cvterm sym ON sym.cvterm_id=symf.cvterm_id
          LEFT JOIN feature_cvtermprop symp ON symp.feature_cvterm_id=symf.feature_cvterm_id 
            AND symp.type_id=(SELECT cvterm_id FROM cvterm 
                              WHERE name='QTL Symbol' 
                                    AND cv_id=(SELECT cv_id FROM cv WHERE name='local'))
          -- ... and use it to get the trait class
          LEFT JOIN (SELECT subject_id, name FROM cvterm c 
                       INNER JOIN cvterm_relationship tcr ON tcr.object_id=c.cvterm_id
                     WHERE tcr.type_id=(SELECT cvterm_id FROM cvterm 
                                       WHERE name='Has Trait Class' 
                                             AND cv_id=(SELECT cv_id FROM cv WHERE name='local'))
                    ) t ON t.subject_id=sym.cvterm_id
      ) tc ON tc.feature_id=q.feature_id
        
      -- trait name and OBO terms
      LEFT JOIN (
        SELECT tnf.feature_id, tnt.name AS trait_name, obo.obo_terms
        FROM feature q2 
          -- get QTL symbol 
          LEFT JOIN feature_cvterm tnf ON tnf.feature_id=q2.feature_id 
          LEFT JOIN cvterm tnt ON tnt.cvterm_id=tnf.cvterm_id
          LEFT JOIN feature_cvtermprop tnp ON tnp.feature_cvterm_id=tnf.feature_cvterm_id 
            AND tnp.type_id=(SELECT cvterm_id FROM cvterm 
                              WHERE name='QTL Symbol' 
                                    AND cv_id=(SELECT cv_id FROM cv WHERE name='local'))
          -- ... and use it to get the trait name
          LEFT JOIN (SELECT subject_id, name FROM cvterm c 
                       INNER JOIN cvterm_relationship tnr ON tnr.object_id=c.cvterm_id
                     WHERE tnr.type_id=(SELECT cvterm_id FROM cvterm 
                                       WHERE name='Has Trait Name' 
                                             AND cv_id=(SELECT cv_id FROM cv WHERE name='local'))
                    ) t ON t.subject_id=tnt.cvterm_id
          LEFT JOIN (
            SELECT t.cvterm_id, ARRAY_TO_STRING(ARRAY_AGG(dbx.accession), ',') AS obo_terms 
            FROM cvterm t
              INNER JOIN cv ON cv.cv_id=t.cv_id
              LEFT JOIN (
                SELECT cd.cvterm_id, dx.dbxref_id, (db.name||':'||dx.accession) AS accession 
                FROM cvterm_dbxref cd 
                  INNER JOIN dbxref dx ON dx.dbxref_id=cd.dbxref_id
                  INNER JOIN db ON db.db_id=dx.db_id
              ) dbx ON dbx.cvterm_id=t.cvterm_id
            WHERE cv.name='LegumeInfo:traits'
            GROUP BY t.cvterm_id
          ) obo ON obo.cvterm_id=tnt.cvterm_id
        ) tn ON tn.feature_id=q.feature_id
        
      -- Favorable Allele Source
      LEFT JOIN feature_stock fs 
        ON fs.feature_id=q.feature_id
           AND fs.type_id=(SELECT cvterm_id FROM chado.cvterm 
                           WHERE name='Favorable Allele Source'
                                AND cv_id=(SELECT cv_id FROM chado.cv 
                                           WHERE name='local'))
      LEFT JOIN stock s ON s.stock_id=fs.stock_id
      LEFT JOIN public.chado_stock cs on cs.stock_id=s.stock_id
    
      -- treatment
      LEFT JOIN featureprop tmt ON tmt.feature_id = q.feature_id
        AND tmt.type_id=(SELECT cvterm_id FROM chado.cvterm 
                         WHERE name='QTL Study Treatment'
                               AND cv_id=(SELECT cv_id FROM chado.cv 
                                          WHERE name='feature_property'))
    
      -- analysis method
      LEFT JOIN featureprop meth ON meth.feature_id = q.feature_id
        AND meth.type_id=(SELECT cvterm_id FROM chado.cvterm 
                          WHERE name='QTL Analysis Method'
                                AND cv_id=(SELECT cv_id FROM chado.cv 
                                           WHERE name='feature_property'))
    
      -- LOD
      LEFT JOIN (
        SELECT af.feature_id, af.rawscore
        FROM analysis a 
          INNER JOIN analysisfeature af ON af.analysis_id=a.analysis_id
        WHERE a.name='LOD'
      ) lod ON lod.feature_id=q.feature_id
    
      -- likelihood ratio
      LEFT JOIN (
        SELECT af.feature_id, af.rawscore FROM analysis a 
          INNER JOIN analysisfeature af ON af.analysis_id=a.analysis_id
        WHERE a.name='likelihood ratio'
      ) lr ON lr.feature_id=q.feature_id
      
      -- marker R2
      LEFT JOIN (
        SELECT af.feature_id, af.rawscore FROM analysis a 
          INNER JOIN analysisfeature af ON af.analysis_id=a.analysis_id
        WHERE a.name='marker R2'
      ) mr2 ON mr2.feature_id=q.feature_id
      
      -- total R2
      LEFT JOIN (
        SELECT af.feature_id, af.rawscore FROM analysis a 
          INNER JOIN analysisfeature af ON af.analysis_id=a.analysis_id
        WHERE a.name='total R2'
      ) tr2 ON tr2.feature_id=q.feature_id
      
      -- additivity
      LEFT JOIN (
        SELECT AF.feature_id, AF.rawscore FROM analysis A 
          INNER JOIN analysisfeature AF ON AF.analysis_id=A.analysis_id
        WHERE A.name='additivity'
      ) add ON add.feature_id=q.feature_id  
    
      -- nearest marker
      LEFT JOIN feature_relationship nmr
        ON nmr.subject_id=q.feature_id 
          AND nmr.type_id=(SELECT cvterm_id FROM chado.cvterm 
             WHERE name='Nearest Marker' 
               AND cv_id=(SELECT cv_id FROM chado.cv 
                          WHERE name='feature_relationship'))
      LEFT JOIN feature nm ON nm.feature_id=nmr.object_id
      LEFT JOIN public.chado_feature cnm ON cnm.feature_id = nm.feature_id
      
      -- flanking marker low
      LEFT JOIN feature_relationship fmlr 
        ON fmlr.subject_id=q.feature_id 
           AND fmlr.type_id=(SELECT cvterm_id FROM chado.cvterm 
                             WHERE name='Flanking Marker Low' 
                                   AND cv_id=(SELECT cv_id FROM chado.cv 
                                              WHERE name='feature_relationship'))
      LEFT JOIN feature fml ON fml.feature_id=fmlr.object_id
      LEFT JOIN public.chado_feature cfml ON cfml.feature_id = fml.feature_id
    
      -- flanking marker high
      LEFT JOIN feature_relationship fmhr ON fmhr.subject_id=q.feature_id 
        AND FMHR.type_id=(SELECT cvterm_id FROM chado.cvterm 
                          WHERE name='Flanking Marker High' 
                                AND cv_id=(SELECT cv_id FROM chado.cv 
                                           WHERE name='feature_relationship'))
      LEFT JOIN feature fmh ON fmh.feature_id=fmhr.object_id
      LEFT JOIN public.chado_feature cfmh ON cfmh.feature_id = fmh.feature_id
        
      -- comment
      LEFT JOIN featureprop comm ON comm.feature_id = q.feature_id
        AND comm.type_id=(SELECT cvterm_id FROM chado.cvterm 
                         WHERE name='comment'
                               AND cv_id=(SELECT cv_id FROM chado.cv 
                                          WHERE name='feature_property'))
    
     WHERE q.type_id=(SELECT cvterm_id FROM cvterm 
                     WHERE name='QTL'
                           AND cv_id=(SELECT cv_id FROM chado.cv 
                                      WHERE name='sequence'))";
  
  // Describes the table qtl_search
  $schema = array (
    'table' => 'qtl_search',
    'fields' => array(
      'qtl_id' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'qtl_nid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'qtl_name' => array(
        'type' => 'text',
        'not null' => TRUE,
      ),
      'expt_qtl_symbol' => array(
        'type' => 'text',
        'NOT NULL' => TRUE,
      ),
      'organism' => array(
        'type' => 'varchar',
        'length' => '510',
        'not null' => TRUE,
      ),
      'common_name' => array(
        'type' => 'varchar',
        'length' => '510',
        'not null' => TRUE,
      ),
      'org_nid' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'mnemonic' => array(
        'type' => 'varchar',
        'length' => '10',
        'not null' => TRUE,
      ),
      'citation' => array(
        'type' => 'text',
        'not null' => TRUE,
      ),
      'pub_nid' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'expt_trait_name' => array(
        'type' => 'text',
        'NOT NULL' => TRUE,
      ),
      'expt_trait_description' => array(
        'type' => 'text',
        'NOT NULL' => TRUE,
      ),
      'trait_unit' => array(
        'type' => 'varchar',
        'length' => '255',
        'NOT NULL' => FALSE,
      ),
      'trait_class' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
       'qtl_symbol' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'trait_name' => array(
        'type' => 'varchar',
        'length' => '255',
        'NOT NULL' => FALSE,
      ),
      'trait_description' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'obo_terms' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'favorable_allele_source' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'fas_nid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'treatment' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'analysis_method' => array(
        'type' => 'text',
        'NOT NULL' => FALSE,
      ),
      'lod' => array(
        'type' => 'float',
        'not null' => FALSE,
      ),
      'likelihood_ratio' => array(
        'type' => 'float',
        'not null' => FALSE,
      ),
      'marker_r2' => array(
        'type' => 'float',
        'not null' => FALSE,
      ),
      'total_r2' => array(
        'type' => 'float',
        'not null' => FALSE,
      ),
      'additivity' => array(
        'type' => 'float',
        'not null' => FALSE,
      ),
      'nearest_marker' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'nearest_marker_nid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'flanking_marker_low' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'flanking_marker_low_nid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'flanking_marker_high' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'flanking_marker_high_nid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'comment' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'QTL_search_indx0' => array('organism'),
      'QTL_search_indx2' => array('expt_qtl_symbol'),
      'QTL_search_indx3' => array('qtl_symbol'),
      'QTL_search_indx4' => array('trait_class'),
      'QTL_search_indx5' => array('obo_terms'),
    ),
  );
  
  // add a comment to make sure this view makes sense to the site administator
  $comment = t('This view is used to provide a table for searching QTLs.');
  tripal_add_mview(
    'qtl_search', // name of materialized view
    'legume_qtl', // name of module submitting view
    $schema,      // schema api array representation
    $sql,         // sql query that loads the mview
    $comment );
}


/**
 * Integrate the qtl_search materialized view for use by Drupal Views and
 * our search form
 */
function legume_qtl_views_integrate_qtl_search() {
  $integration = array (
    'table' => 'qtl_search',
    'name' => 'QTL',
    'type' => 'chado',
    'description' => '',
    'priority' => '-1',
    'base_table' => '1',
    'fields' => array (
      'additivity' => array (
        'name' => 'additivity',
        'title' => 'Additivity',
        'description' => 'Additivity',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'analysis_method' => array (
        'name' => 'analysis_method',
        'title' => 'Analysis method',
        'description' => 'QTL analysis method',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'citation' => array (
        'name' => 'citation',
        'title' => 'Citation',
        'description' => 'Publication citation',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'comment' => array (
        'name' => 'comment',
        'title' => 'Comment',
        'description' => 'Comment',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'common_name' => array (
        'name' => 'common_name',
        'title' => 'common name',
        'description' => 'Organism common name',
        'type' => 'varchar',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'expt_qtl_symbol' => array (
        'name' => 'expt_qtl_symbol',
        'title' => 'QTL name used in publication',
        'description' => 'QTL name used in experiment',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'expt_trait_name' => array (
        'name' => 'expt_trait_name',
        'title' => 'Experimental Trait Name',
        'description' => 'Trait name used in experiment',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'expt_trait_description' => array (
        'name' => 'expt_trait_description',
        'title' => 'Experimental Trait Description',
        'description' => 'Trait description from experiment',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'obo_terms' => array (
        'name' => 'obo_terms',
        'title' => 'Associated ontology terms',
        'description' => 'Ontology term associated with this trait',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'favorable_allele_source' => array (
        'name' => 'favorable_allele_source',
        'title' => 'Favorable Allele Source',
        'description' => 'Parent with the favorable allele',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'fas_nid' => array (
        'name' => 'fas_nid',
        'title' => 'fas_nid',
        'description' => 'Favorable Allele Source nid',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),

      'flanking_marker_high' => array (
        'name' => 'flanking_marker_high',
        'title' => 'Right Flanking Marker',
        'description' => 'Right flanking marker',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'flanking_marker_high_nid' => array (
        'name' => 'flanking_marker_high_nid',
        'title' => 'Right Flanking Marker NID',
        'description' => 'Right flanking marker NID',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'flanking_marker_low' => array (
        'name' => 'flanking_marker_low',
        'title' => 'Left Flanking Marker',
        'description' => 'Left flanking marker',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'flanking_marker_low_nid' => array (
        'name' => 'flanking_marker_low_nid',
        'title' => 'Left Flanking Marker NID',
        'description' => 'Left flanking marker NID',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'genus' => array (
        'name' => 'genus',
        'title' => 'Genus',
        'description' => 'Organism genus',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'interval_calc_method' => array (
        'name' => 'interval_calc_method',
        'title' => 'Interval Calculation Method',
        'description' => 'Method used to calculate map intervals',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'likelihood_ratio' => array (
        'name' => 'likelihood_ratio',
        'title' => 'Likelihood Ratio',
        'description' => 'Likelihood ratio',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'lod' => array (
        'name' => 'lod',
        'title' => 'LOD',
        'description' => 'LOD',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'marker_r2' => array (
        'name' => 'marker_r2',
        'title' => 'Marker R2',
        'description' => 'Marker R2',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'mnemonic' => array (
        'name' => 'mnemonic',
        'title' => 'Species mnemonic',
        'description' => 'Species mnemonic',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'nearest_marker' => array (
        'name' => 'nearest_marker',
        'title' => 'Nearest Marker',
        'description' => 'Nearest marker',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'nearest_marker_nid' => array (
        'name' => 'nearest_marker_nid',
        'title' => 'Nearest Marker NID',
        'description' => 'Nearest marker NID',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'obo_terms' => array (
        'name' => 'obo_terms',
        'title' => 'Associated ontology terms',
        'description' => 'Ontology terms associated with this trait',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'org_nid' => array (
        'name' => 'org_nid',
        'title' => 'org_nid',
        'description' => 'Organism nid',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'organism' => array (
        'name' => 'organism',
        'title' => 'organism',
        'description' => 'Organism name',
        'type' => 'varchar',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'pub_nid' => array (
        'name' => 'pub_nid',
        'title' => 'pub_nid',
        'description' => 'Publication nid',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'qtl_id' => array (
        'name' => 'qtl_id',
        'title' => 'qtl_id',
        'description' => 'QTL ID',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'qtl_name' => array (
        'name' => 'qtl_name',
        'title' => 'QTL name',
        'description' => 'QTL name',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'qtl_nid' => array (
        'name' => 'qtl_nid',
        'title' => 'qtl_nid',
        'description' => 'QTL nid',
        'type' => 'int',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
      'qtl_symbol' => array (
        'name' => 'qtl_symbol',
        'title' => 'QTL Symbol',
        'description' => 'QTL symbol',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'species' => array (
        'name' => 'species',
        'title' => 'Species',
        'description' => 'Organism species',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'trait_class' => array (
        'name' => 'trait_class',
        'title' => 'Trait class',
        'description' => 'Trait class',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'tripal_views_handler_filter_select_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'trait_name' => array (
        'name' => 'trait_name',
        'title' => 'Trait Name',
        'description' => 'Official Trait Name',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'trait_description' => array (
        'name' => 'trait_description',
        'title' => 'Trait Description',
        'description' => 'Trait description',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'trait_unit' => array (
        'name' => 'trait_unit',
        'title' => 'Trait unit',
        'description' => 'Trait unit',
        'type' => 'varchar',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'treatment' => array (
        'name' => 'treatment',
        'title' => 'QTL treatment',
        'description' => 'QTL study treatment',
        'type' => 'text',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_string',
          ),
          'field' => array (
            'name' => 'views_handler_field',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_string',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
      
      'total_r2' => array (
        'name' => 'total_r2',
        'title' => 'Total R2',
        'description' => 'Total R2',
        'type' => 'float',
        'handlers' => array (
          'filter' => array (
            'name' => 'views_handler_filter_numeric',
          ),
          'field' => array (
            'name' => 'views_handler_field_numeric',
          ),
          'sort' => array (
            'name' => 'views_handler_sort',
          ),
          'argument' => array (
            'name' => 'views_handler_argument_numeric',
          ),
          'relationship' => array (
            'name' => 'views_handler_relationship',
          ),
        ),
        'joins' => array (
        ),
      ),
  
    ),
  );  

  // add the array above that will integrate our qtl_search materialized view
  // for use with Drupal Views
  tripal_views_integration_add_entry($integration); 
}